### ISSUE TITLE
DL Workshop thumbnail abnormally large

### ISSUE THREAD

**Issue by adrianleh** [hackundsoehne/hs-website#9]
![screen shot 2018-06-04 at 11 03 33](https://user-images.githubusercontent.com/26521502/40908418-fd8c509c-67e6-11e8-9b03-ff473b6ba1e6.png)

**Comment by MaximilianFranz** [comment]
This website is shit. All png. need to be 800x450 to fit exactly in the frame. Zero intelligent, maximum effort for every fucking picture :D

**Comment by adrianleh** [comment]
@MaximilianFranz I know. But right now we need to work it. Unfortunately...
